{% set name = "duckdb-engine" %}
{% set package_name = name | replace("-", "_") %}
{% set version = "0.13.5" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ package_name }}/{{ package_name }}-{{ version }}.tar.gz
  sha256: 5265cf2401c7053d34ceb8222cf03eb5e7a51c73e999ad4b286769e3546e9532

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
  run:
    - python >={{ python_min }}
    - python-duckdb >=0.5.0
    - sqlalchemy >=1.3.22
    - packaging >=21.3

test:
  requires:
    - python {{ python_min }}
    - pyarrow
    - pytest >=8.0.0,<9
    - pytest-remotedata >=0.4.0,<0.5
    - hypothesis >=6.75.2,<7
    - pandas >=1,<2
    - snapshottest >=0.6.0,<0.7
  imports:
    - duckdb_engine
  commands:
    - pytest --pyargs duckdb_engine

about:
  home: https://github.com/Mause/duckdb_engine
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: SQLAlchemy driver for duckdb
  description: SQLAlchemy driver for duckdb
  dev_url: https://github.com/Mause/duckdb_engine

extra:
  recipe-maintainers:
    - gforsyth
    - cpcloud
    - pavelzw
