{% set name = "duckdb-engine" %}
{% set package_name = name | replace("-", "_") %}
{% set version = "0.11.5" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ package_name }}/{{ package_name }}-{{ version }}.tar.gz
  sha256: a9419647b0cf480b4ad73add05d30cc6762c7d542ec14a0d4b477f8a96a58892

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - python-duckdb >=0.4.0
    - sqlalchemy >=1.3.19
    - packaging >=21.3

test:
  requires:
    - pytest >=7,<8
    - pytest-remotedata >=0.4
    - hypothesis >=6.68.2,<7
    - pandas >=1,<2
  imports:
    - duckdb_engine
  commands:
    - pytest --pyargs duckdb_engine

about:
  home: https://github.com/Mause/duckdb_engine
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: SQLAlchemy driver for duckdb
  description: SQLAlchemy driver for duckdb
  dev_url: https://github.com/Mause/duckdb_engine

extra:
  recipe-maintainers:
    - gforsyth
    - cpcloud
